def P_adminLinearIndex2():
  set_tcp(p[0.0,0.0,0.076,0.7245313926163333,-1.7654607319513724,1.7638170400690123])
  set_payload(1.0)
  set_standard_analog_input_domain(0, 0)
  set_standard_analog_input_domain(1, 0)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  step_count_3b565969_7e16_419d_8180_cc4310da6b74 = 0.0
  thread Step_Counter_Thread_dc96f478_d0a4_442a_9de6_1af2e01e986a():
    while (True):
      step_count_3b565969_7e16_419d_8180_cc4310da6b74 = step_count_3b565969_7e16_419d_8180_cc4310da6b74 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_dc96f478_d0a4_442a_9de6_1af2e01e986a()
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(0)
  modbus_add_signal("127.0.0.1", 255, 1, 3, "MODBUS_1", False)
  modbus_set_signal_update_frequency("MODBUS_1", 10)
  modbus_add_signal("127.0.0.1", 255, 203, 3, "MODBUS_2", False)
  modbus_set_signal_update_frequency("MODBUS_2", 10)
  modbus_set_runstate_dependent_choice("MODBUS_1",0)
  modbus_set_runstate_dependent_choice("MODBUS_2",0)
  set_tool_voltage(0)
  global stock_spacing=76.2
  global Gravity_Feeder=p[0.26545424739685874,-0.423573422243878,0.3571526050789449,0.1619581347920129,-0.4133494768613531,-2.317499916011395]
  global Linear_Slide=p[0.26542544581166166,-0.4235747955277341,0.35716918848305357,-0.010251867852105759,-0.0039919442596599315,-2.348075206071431]
  # begin: URCap Installation Node
  #   Source: VersaBuilt Robot2CNC, 2.0.9, VersaBuilt Robotics Inc.
  #   Type: R2C Config
  global vbSaveR2CIPAddr = "10.241.34.40"
  global vbSaveDoor = "SingleDoor"
  global vbSaveDoorSensors = True
  global vbSaveDoorWaitTime = 0
  global vbSaveViseSensors = True
  # end: URCap Installation Node
  $ 1 "Robot Program"
  $ 2 "Move_linear_slide_Index2"
  $ 3 "var_1≔ False "
  global var_1=  False  
  $ 4 "Loop var_1≟ False "
  while (var_1 ==   False  ):
    $ 5 "var_1≔socket_open('10.241.34.52',4001)"
    global var_1=socket_open("10.241.34.52",4001)
  end
  $ 6 "var_3≔1"
  global var_3=1
  $ 7 "Send≔'s r0x24 21'"
  global Send="s r0x24 21"
  $ 8 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 9 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 10 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 11 "Send≔'s r0xca 56389'"
  global Send="s r0xca 56389"
  $ 12 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 13 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 14 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 15 "Send≔'t 1'"
  global Send="t 1"
  $ 16 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 17 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 18 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 19 "Loop var_3≠0"
  while (var_3 != 0):
    $ 20 "Send≔'g r0xA0'"
    global Send="g r0xA0"
    $ 21 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 22 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 23 "var_3≔socket_get_var('v')"
    global var_3=socket_get_var("v")
    $ 24 "Wait: 0.1"
    sleep(0.1)
  end
  $ 25 "socket_close()"
  socket_close()
  $ 26 "sync()"
  sync()
end
