def Short_Body_UnloadMill_Tier1():
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(0)
  modbus_add_signal("127.0.0.1", 255, 1, 3, "MODBUS_1", False)
  modbus_set_signal_update_frequency("MODBUS_1", 10)
  modbus_add_signal("127.0.0.1", 255, 203, 3, "MODBUS_2", False)
  modbus_set_signal_update_frequency("MODBUS_2", 10)
  modbus_set_runstate_dependent_choice("MODBUS_1",0)
  modbus_set_runstate_dependent_choice("MODBUS_2",0)
  set_standard_analog_input_domain(0, 0)
  set_standard_analog_input_domain(1, 0)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[0.0,0.0,0.076,0.7245313926163333,-1.7654607319513724,1.7638170400690123])
  set_payload(1.0)
  set_tool_voltage(0)
  step_count_757b1681_df85_4cfd_b3b8_54b09f90c0f6 = 0.0
  thread Step_Counter_Thread_46c502e7_6676_4da3_bba1_7a0b6ed7b64a():
    while (True):
      step_count_757b1681_df85_4cfd_b3b8_54b09f90c0f6 = step_count_757b1681_df85_4cfd_b3b8_54b09f90c0f6 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_46c502e7_6676_4da3_bba1_7a0b6ed7b64a()
  global stock_spacing=76.2
  global Gravity_Feeder=p[0.26545424739685874,-0.423573422243878,0.3571526050789449,0.1619581347920129,-0.4133494768613531,-2.317499916011395]
  global Linear_Slide=p[0.26542544581166166,-0.4235747955277341,0.35716918848305357,-0.010251867852105759,-0.0039919442596599315,-2.348075206071431]
  # begin: URCap Installation Node
  #   Source: VersaBuilt Robot2CNC, 2.0.9, VersaBuilt Robotics Inc.
  #   Type: R2C Config
  global vbSaveR2CIPAddr = "10.241.34.40"
  global vbSaveDoor = "SingleDoor"
  global vbSaveDoorSensors = True
  global vbSaveDoorWaitTime = 0
  global vbSaveViseSensors = True
  # end: URCap Installation Node
  def _adminLinearIndex4():
    $ 27 "_adminLinearIndex4" "noBreak"
    $ 28 "Move_linear_slide_Index4"
    $ 29 "var_1≔ False "
    global var_1=  False  
    $ 30 "Loop var_1≟ False "
    while (var_1 ==   False  ):
      $ 31 "var_1≔socket_open('10.241.34.52',4001)"
      global var_1=socket_open("10.241.34.52",4001)
    end
    $ 32 "var_3≔1"
    global var_3=1
    $ 33 "Send≔'s r0x24 21'"
    global Send="s r0x24 21"
    $ 34 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 35 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 36 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 37 "Send≔'s r0xca 169167'"
    global Send="s r0xca 169167"
    $ 38 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 39 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 40 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 41 "Send≔'t 1'"
    global Send="t 1"
    $ 42 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 43 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 44 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 45 "Loop var_3≠0"
    while (var_3 != 0):
      $ 46 "Send≔'g r0xA0'"
      global Send="g r0xA0"
      $ 47 "socket_send_string(Send)"
      socket_send_string(Send)
      $ 48 "socket_send_byte(13)"
      socket_send_byte(13)
      $ 49 "var_3≔socket_get_var('v')"
      global var_3=socket_get_var("v")
      $ 50 "Wait: 0.1"
      sleep(0.1)
    end
    $ 51 "socket_close()"
    socket_close()
    $ 52 "sync()"
    sync()
  end
  $ 1 "BeforeStart"
  $ 2 "Script: R2CScript.script"
  # Copyright 2020 VersaBuilt, Inc. All Rights Reserved
  
  global vbR2CIPAddr = "192.168.2.1"
  global vbR2CPort = 9002
  global vbVersaBlast = "VERSABLAST"
  global vbGripperOpen = "GRIPPER_OPEN"
  global vbGripperClose = "GRIPPER_CLOSE"
  global vbVise1Open = "VISE_1_OPEN"
  global vbVise1Close = "VISE_1_CLOSE"
  global vbVise1Sensor = "VISE_1_SENSOR"
  global vbVise2Open = "VISE_2_OPEN"
  global vbVise2Close = "VISE_2_CLOSE"
  global vbVise2Sensor = "VISE_2_SENSOR"
  global vbDoorOpen = "DOOR_OPEN"
  global vbDoorOpenSensor = "DOOR_OPEN_SENSOR"
  global vbDoorOpenSensor2 = "DOUBLE_DOOR_OPEN_SENSOR"
  global vbDoorClose = "DOOR_CLOSE"
  global vbDoorCloseSensor = "DOOR_CLOSE_SENSOR"
  global vbDoorCloseSensor2 = "DOUBLE_DOOR_CLOSE_SENSOR"
  global vbDoor = "SingleDoor"
  global vbDoorWaitTime = 7
  global vbDoorTimeOut = 15
  global vbDoorSensors = True
  global vbViseSensors = True
  global vbSim = False
  
  def InitializeR2CVars():
    vbR2CIPAddr = vbSaveR2CIPAddr
    vbDoor = vbSaveDoor
    vbDoorSensors = vbSaveDoorSensors
    vbViseSensors = vbSaveViseSensors
    vbDoorWaitTime = vbSaveDoorWaitTime
  end
  
  def SetIPAddr(ip):
    vbSaveR2CIPAddr = ip
  end
  
  # Send a R2C Command. If the response is an error, a blocking popup will be generated.
  # Otherwise the response is returned
  def SendR2CCommand(text):
    response = SendR2CCommandRaw(text)
    CheckR2CResponse(response)
    return response
  end
  
  # Reads a R2C response and creates a blocking popup if an error is detected
  def CheckR2CResponse(response):
    errorPortion = str_sub(response, 0, 5)
    if (errorPortion == "ERROR"):
      popup("Robot2CNC Error, press the Stop Program button and resolve the error condition: " + response, error = True, blocking = True)
      halt
    end
  end
  
  def OpenSocket():
    count = 0
    socket_result = socket_open(vbR2CIPAddr, vbR2CPort, "socket_1")
    while (not(socket_result) and count < 10):
      sleep(1)
      count = count + 1
      socket_result = socket_open(vbR2CIPAddr, vbR2CPort, "socket_1")
    end
    if not(socket_result):
      popup("Communication with Robot2CNC Failed (socket open). Press the Stop Program button and fix the Robot2CNC communication problem.", "Robot2CNC Command Error", error = True, blocking = True)
      halt
    end
  end
  
  # Send a R2C command, return the response. Does not check response for error.
  def SendR2CCommandRaw(text):
    InitializeR2CVars()
    count = 0
    while count < 3:
      count = count + 1
      OpenSocket()
      socket_send_line(text, "socket_1")
      status = socket_read_string("socket_1", "", ";", True, 5)
      socket_close("socket_1")
      if str_len(status) > 0:
        return status
      end
      sleep(1)
    end
    popup("Communication with Robot2CNC Failed (no response). Press the Stop Program button and fix the Robot2CNC communication problem.", "Robot2CNC Command Error", error = True, blocking = True)
    halt
  end
  
  def VersaBlastOn():
      if vbSim == False:
          SetDO(vbVersaBlast, "ON")
      end
  end
  
  def VersaBlastOff():
      if vbSim == False:
          SetDO(vbVersaBlast, "OFF")
      end
  end
  
  def OpenGripper():
      if vbSim == False:
          SetDO(vbGripperClose, "OFF")
          SetDO(vbGripperOpen, "ON")
      end
  end
  
  def CloseGripper():
      if vbSim == False:
          SetDO(vbGripperClose, "ON")
          SetDO(vbGripperOpen, "OFF")
      end
  end
  
  def FloatGripper():
      if vbSim == False:
          SetDO(vbGripperClose, "OFF")
          SetDO(vbGripperOpen, "OFF")
      end
  end
  
  def OpenVise(viseNum):
    if vbSim == False:
      if viseNum == 1 :
        SetDO(vbVise1Close, "OFF")
        SetDO(vbVise1Open, "ON")
      else:
        SetDO(vbVise2Close, "OFF")
        SetDO(vbVise2Open, "ON")
      end
    end
  end
  
  def CloseVise(viseNum):
    if vbSim == False:
      if viseNum == 1 :
        SetDO(vbVise1Open, "OFF")
        SetDO(vbVise1Close, "ON")
      else:
        SetDO(vbVise2Open, "OFF")
        SetDO(vbVise2Close, "ON")
      end
    end
  end
  
  def ViseFumbleCheck(viseNum):
    if vbSim == False:
      InitializeR2CVars()
      if vbViseSensors:
        if viseNum == 1:
          if (GetDI(vbVise1Sensor) == "OFF"):
            popup("Vise fumble. The VB Mill App Kit could not confirm the part was loaded in the vise. Exiting","VB Mill App Kit",error= True, blocking=True)
            halt
          end
        else:
          if (GetDI(vbVise2Sensor) == "OFF"):
            popup("Vise fumble. The VB Mill App Kit could not confirm the part was loaded in the vise. Exiting","VB Mill App Kit",error= True, blocking=True)
            halt
          end
        end
      end
    end
  end
  
  # clamps a vise by moving in the direction specified by ODID
  def ClampVise(viseNum,ODID):
    if vbSim == False:
      if (ODID == "OD"):
        CloseVise(viseNum)
      else:
        OpenVise(viseNum)
      end
    end
  end
  
  def UnClampVise(viseNum,ODID):
    if vbSim == False:
      if (ODID == "OD"):
        OpenVise(viseNum)
      else:
        CloseVise(viseNum)
      end
    end
  end
  
  def OpenDoor():
    if vbSim == False:
      InitializeR2CVars()
      if vbDoor != "CNCDoor" :
        SetDO(vbDoorClose, "OFF")
        SetDO(vbDoorOpen, "ON")
        if vbDoorSensors == True :
          vbDoorTimeOutCounter = 0
          while GetDI(vbDoorOpenSensor) == "OFF" :
            sleep(.1)
            vbDoorTimeOutCounter = vbDoorTimeOutCounter + 0.1
            if vbDoorTimeOutCounter >= vbDoorTimeOut :
              FloatDoor()
              popup("Door failed to open within " + to_str(vbDoorTimeOut) + " seconds (door sensor 1).<br><br>Fix the problem, open the door and press Continue or press the Stop button.", blocking = True)
              vbDoorTimeOutCounter = 0
            end
          end
          # if we have double doors, check the double door sensor
          if (vbDoor == "DoubleDoor") :
            vbDoorTimeOutCounter = 0
            while GetDI(vbDoorOpenSensor2) == "OFF" :
              sleep(.1)
              vbDoorTimeOutCounter = vbDoorTimeOutCounter + 0.1
              if vbDoorTimeOutCounter >= vbDoorTimeOut :
                FloatDoor()
                popup("Door failed to open within " + to_str(vbDoorTimeOut) + " seconds (door sensor 2).<br><br>Fix the problem, open the door and press Continue or press the Stop button.", blocking = True)
                vbDoorTimeOutCounter = 0
              end
            end
          end
        else:
          sleep(vbDoorWaitTime)
        end
        # give it another second to open all the way...
        sleep(1)
        # Float the door after open/close
        FloatDoor()
      else:
        sleep(vbDoorWaitTime)
      end
    end
  end
  
  def CloseDoor():
    if vbSim == False:
      InitializeR2CVars()
      if vbDoor != "CNCDoor" :
        SetDO(vbDoorOpen, "OFF")
        SetDO(vbDoorClose, "ON")
        if vbDoorSensors == True :
          vbDoorTimeOutCounter = 0
          while GetDI(vbDoorCloseSensor) == "OFF" :
            sleep(.1)
            vbDoorTimeOutCounter = vbDoorTimeOutCounter + 0.1
            if vbDoorTimeOutCounter >= vbDoorTimeOut :
              FloatDoor()
              popup("Door failed to close within " + to_str(vbDoorTimeOut) + " seconds (door sensor 1).<br><br>Fix the problem, open the door and press Continue or press the Stop button.", blocking = True)
              vbDoorTimeOutCounter = 0
            end
          end
          # if we have double doors, check the double door sensor
          if (vbDoor == "DoubleDoor") :
            vbDoorTimeOutCounter = 0
            while GetDI(vbDoorCloseSensor2) == "OFF" :
              sleep(.1)
              vbDoorTimeOutCounter = vbDoorTimeOutCounter + 0.1
              if vbDoorTimeOutCounter >= vbDoorTimeOut :
                FloatDoor()
                popup("Door failed to close within " + to_str(vbDoorTimeOut) + " seconds (door sensor 2).<br><br>Fix the problem, open the door and press Continue or press the Stop button.", blocking = True)
                vbDoorTimeOutCounter = 0
              end
            end
          end
        else:
          sleep(vbDoorWaitTime)
        end
        # give it another second to close tight...
        sleep(1)
        # Float door after closing/opening
        FloatDoor()
      else:
        sleep(vbDoorWaitTime)
      end
    end
  end
  
  # Wait for DI at addr to equal value, timeout after specified seconds. Retuens true on success, false on timeout.
  def WaitDI(addr, value, timeout):
    if vbSim == False:
      time = 0
      while GetDI(addr) != value:
        sleep(.1)
        time = time + 0.1
        if time > timeout:
          return False
        end
      end
      return True
    else:
      return True
    end
  end
  
  def SetDO(ioAddress, onOff):
    if vbSim == False:
      command = "SET_DO," + ioAddress + "," + onOff + ";"
      result = SendR2CCommand(command)
      if result + ";" != command:
        popup("Error setting digital output on Robot2CNC, press Stop Program and resolve error.<br>Unable to set " + to_str(ioAddress) + ", " + to_str(onOff), error=True, blocking = True)
        halt
      end
    end
  end
  
  def GetDI(ioAddress):
    if vbSim == False:
      command = "GET_DI," + ioAddress + ";"
      result = SendR2CCommand(command)
      return str_sub(result, str_len(command))
    end
  end
  
  def WaitCNC():
    if vbSim == False:
      status = SendR2CCommand("CNC_STATUS;")
      while (status != "CNC_STATUS,COMPLETE"):
        status = SendR2CCommand("CNC_STATUS;")
        sleep(0.5)
      end
      if (status != "CNC_STATUS,COMPLETE"):
        popup("Can not Validate Program Completion<br>CNC Status: " + status, "Milling Program Not Complete", False, False, blocking = True)
        halt
      else:
        SendR2CCommand("RESET_CNC;")
      end
    end
  end
  
  def FloatVise(viseNum):
    if vbSim == False:
      if viseNum == 1 :
        SetDO(vbVise1Open, "OFF")
        SetDO(vbVise1Close, "OFF")
      else:
        SetDO(vbVise2Open, "OFF")
        SetDO(vbVise2Close, "OFF")
      end
    end
  end
  
  def FloatDoor():
    if vbSim == False:
      SetDO(vbDoorOpen, "OFF")
      SetDO(vbDoorClose, "OFF")
    end
  end
  
  def RunCNCProgram(progNum):
    if vbSim == False:
      status = SendR2CCommand("CNC_STATUS;")
      if not(status == "CNC_STATUS,IDLE" or status == "CNC_STATUS,COMPLETE"):
        popup("CNC Not Idle. Press Stop Program and resolve problem on CNC.<br>Result from CNC: " + status, "CNC Not Ready", False, False, blocking = True)
        halt
      end
      SendR2CCommand("RUN_PROGRAM,"+to_str(progNum)+";")
    end
  end
  
  def SetHaasCellSafe():
    if vbSim == False:
      SendR2CCommand("ENABLE_HAAS_CELL_SAFE;")
    end
    sleep(0.1)
  end
  
  def ClearHaasCellSafe():
    if vbSim == False:
      SendR2CCommand("DISABLE_HAAS_CELL_SAFE;")
    end
  end
  
  def GetMacro(macroNum):
    if vbSim == False :
      send = "READ_MACRO,"+to_str(macroNum)
      length = str_len(send)
      result = SendR2CCommand(send+";")
      return to_num(str_sub(result,length+1))
    else:
      return 0
    end
  end
  
  def SetMacro(macroNum, value):
    if vbSim == False:
      result = SendR2CCommand("WRITE_MACRO,"+to_str(macroNum)+","+to_str(value)+";")
    end
  end
  $ 3 "Robot Program"
  # begin: URCap Program Node
  #   Source: VersaBuilt Robot2CNC, 2.0.9, VersaBuilt Robotics Inc.
  #   Type: Robot2CNC
  $ 5 "Run CNC Program"
  SetIPAddr("10.241.34.40")
  RunCNCProgram(100)
  # end: URCap Program Node
  # begin: URCap Program Node
  #   Source: VersaBuilt Robot2CNC, 2.0.9, VersaBuilt Robotics Inc.
  #   Type: Robot2CNC
  $ 6 "Wait for CNC Program"
  SetIPAddr("10.241.34.40")
  WaitCNC()
  ClearHaasCellSafe()
  # end: URCap Program Node
  $ 7 "MoveJ"
  $ 8 "pHome" "breakAfter"
  movej(get_inverse_kin(p[.267143017205, -.421454805117, .355857452843, 1.113981300153, 1.106019241299, .005119613236], qnear=[-0.785346810017721, -1.570820156727926, -1.5707710425006312, -1.570820156727926, 1.5708600282669067, 1.3107746781315655E-4]), a=1.3962634015954636, v=1.0471975511965976)
  $ 9 "Call _adminLinearIndex4"
  _adminLinearIndex4()
  $ 10 "Set DO[1]=Off"
  set_standard_digital_out(1, False)
  $ 11 "MoveJ"
  $ 12 "Crouch" "breakAfter"
  movej(get_inverse_kin(p[-.109146893103, -.260509829412, .170948981390, 1.676540927221, .134441821397, -1.082344358461], qnear=[-1.5708158651935022, -1.0739405790912073, -2.41420823732485, -1.2273066679583948, 1.5708481073379517, 0.6200514435768127]), a=1.3962634015954636, v=3.141592653589793, r=0.1)
  $ 13 "Pivot" "breakAfter"
  movej(get_inverse_kin(p[-.147635173916, .243514111870, .169705501978, 1.568642943090, -1.560033613489, -2.213295581352], qnear=[-3.773529354725973, -1.0826385656939905, -2.414244000111715, -1.216182057057516, 1.5699844360351562, 0.14182880520820618]), a=1.3962634015954636, v=3.141592653589793)
  $ 14 "aboveVise2" "breakAfter"
  movej(get_inverse_kin(p[-.582284265149, .563712810450, .220123809950, 1.568643151189, -1.559073723533, -2.210173743292], qnear=[-3.7758782545672815, -2.410780731831686, -0.716196362172262, -1.5869420210467737, 1.5717120170593262, 0.13726581633090973]), a=1.3962634015954636, v=3.141592653589793)
  $ 15 "MoveL"
  $ 16 "atVise2" "breakAfter"
  movel(p[-.582739314864, .563280461344, .158222830636, 1.568737109632, -1.559106830913, -2.210050754159], a=1.2, v=0.25)
  $ 17 "Set DO[0]=On"
  set_standard_digital_out(0, True)
  $ 18 "Wait: 1.0"
  sleep(1.0)
  $ 19 "Set DO[1]=Off"
  set_standard_digital_out(1, False)
  $ 20 "Wait: 1.0"
  sleep(1.0)
  $ 21 "easeout" "breakAfter"
  movel(p[-.584958307404, .563036244549, .158219449530, 1.568885383801, -1.558955211944, -2.209930272994], a=0.1, v=0.25)
  $ 22 "aboveVise2" "breakAfter"
  movel(p[-.582284265149, .563712810450, .220123809950, 1.568643151189, -1.559073723533, -2.210173743292], a=1.2, v=0.25)
  $ 23 "MoveJ"
  $ 24 "Pivot" "breakAfter"
  movej(get_inverse_kin(p[-.147635173916, .243514111870, .169705501978, 1.568642943090, -1.560033613489, -2.213295581352], qnear=[-3.773529354725973, -1.0826385656939905, -2.414244000111715, -1.216182057057516, 1.5699844360351562, 0.14182880520820618]), a=1.3962634015954636, v=1.0471975511965976)
  $ 25 "Crouch" "breakAfter"
  movej(get_inverse_kin(p[-.109146893103, -.260509829412, .170948981390, 1.676540927221, .134441821397, -1.082344358461], qnear=[-1.5708158651935022, -1.0739405790912073, -2.41420823732485, -1.2273066679583948, 1.5708481073379517, 0.6200514435768127]), a=1.3962634015954636, v=1.0471975511965976, r=0.1)
  $ 26 "pHome" "breakAfter"
  movej(get_inverse_kin(p[.267143017205, -.421454805117, .355857452843, 1.113981300153, 1.106019241299, .005119613236], qnear=[-0.785346810017721, -1.570820156727926, -1.5707710425006312, -1.570820156727926, 1.5708600282669067, 1.3107746781315655E-4]), a=1.3962634015954636, v=1.0471975511965976)
end
