def P_adminCGPHomeToInvC():
  modbus_add_signal("127.0.0.1", 255, 1, 2, "MODBUS_1", False)
  modbus_set_signal_update_frequency("MODBUS_1", 10)
  modbus_add_signal("127.0.0.1", 255, 128, 0, "atLocation", False)
  modbus_set_signal_update_frequency("atLocation", 10)
  modbus_add_signal("127.0.0.1", 255, 129, 2, "MODBUS_3", False)
  modbus_set_signal_update_frequency("MODBUS_3", 10)
  modbus_add_signal("10.241.34.56", 1, 1009, 3, "MODBUS_2", False)
  modbus_set_signal_update_frequency("MODBUS_2", 10)
  modbus_add_signal("10.241.34.37", 1, 0, 3, "vision_result", False)
  modbus_set_signal_update_frequency("vision_result", 10)
  modbus_set_runstate_dependent_choice("MODBUS_2",0)
  modbus_set_runstate_dependent_choice("vision_result",0)
  set_gravity([0.0, 0.0, 9.82])
  step_count_727d1014_d2af_4993_b97d_252ac45b31fc = 0.0
  thread Step_Counter_Thread_b6180ec4_2a1c_4eea_916c_5d5191e43ce3():
    while (True):
      step_count_727d1014_d2af_4993_b97d_252ac45b31fc = step_count_727d1014_d2af_4993_b97d_252ac45b31fc + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_b6180ec4_2a1c_4eea_916c_5d5191e43ce3()
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 0)
  set_tool_analog_input_domain(1, 0)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(1.0)
  set_tool_voltage(0)
  set_safety_mode_transition_hardness(0)
  global hook_index=1
  global visionResult=2
  global num_hooks=6
  global hook_indexB=1
  def _adminLinearIndex3():
    $ 14 "_adminLinearIndex3" "noBreak"
    $ 15 "Move_linear_slide_Index1"
    $ 16 "var_1≔ False "
    global var_1=  False  
    $ 17 "Loop var_1≟ False "
    while (var_1 ==   False  ):
      $ 18 "var_1≔socket_open('10.241.34.44',4001)"
      global var_1=socket_open("10.241.34.44",4001)
    end
    $ 19 "var_3≔1"
    global var_3=1
    $ 20 "Send≔'s r0x24 21'"
    global Send="s r0x24 21"
    $ 21 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 22 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 23 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 24 "Send≔'s r0xca 103936'"
    global Send="s r0xca 103936"
    $ 25 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 26 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 27 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 28 "Send≔'t 1'"
    global Send="t 1"
    $ 29 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 30 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 31 "Send_Reply≔socket_read_string()"
    global Send_Reply=socket_read_string()
    $ 32 "Loop var_3≠0"
    while (var_3 != 0):
      $ 33 "Send≔'g r0xA0'"
      global Send="g r0xA0"
      $ 34 "socket_send_string(Send)"
      socket_send_string(Send)
      $ 35 "socket_send_byte(13)"
      socket_send_byte(13)
      $ 36 "var_3≔socket_get_var('v')"
      global var_3=socket_get_var("v")
      $ 37 "Wait: 0.1"
      sleep(0.1)
    end
    $ 38 "socket_close()"
    socket_close()
    $ 39 "sync()"
    sync()
  end
  $ 1 "Robot Program"
  $ 2 "Call _adminLinearIndex3"
  _adminLinearIndex3()
  $ 3 "Set DO[0]=On"
  set_standard_digital_out(0, True)
  $ 4 "MoveJ"
  $ 5 "pHome" "breakAfter"
  movej(get_inverse_kin(p[.109140646997, -.486905511740, .431874337087, .000009529599, -3.141583114199, .000261860116], qnear=[1.570778727531433, -1.570820156727926, 1.5708212852478027, -1.5709641615497034, -1.57080585161318, -2.366701234990387E-5]), a=1.3962634015954636, v=1.0471975511965976)
  $ 6 "aboveInvC" "breakAfter"
  movej(get_inverse_kin(p[-.123779009197, -.607424363596, .146222018937, 2.221315542908, 2.221298092432, -.000209146068], qnear=[1.1927580833435059, -1.0770600477801722, 1.7191190719604492, -2.213053051625387, -1.570674244557516, 1.1927659511566162]), a=1.3962634015954636, v=1.0471975511965976)
  $ 7 "MoveL"
  $ 8 "atInvC" "breakAfter"
  movel(p[-.123737812280, -.607466592171, .048649880796, 2.221178941952, 2.221428671986, -.000460782114], a=1.2, v=0.25)
  $ 9 "Set DO[0]=Off"
  set_standard_digital_out(0, False)
  $ 10 "Wait: 1.0"
  sleep(1.0)
  $ 11 "aboveInvC" "breakAfter"
  movel(p[-.123779009197, -.607424363596, .146222018937, 2.221315542908, 2.221298092432, -.000209146068], a=1.2, v=0.25)
  $ 12 "MoveJ"
  $ 13 "pHome" "breakAfter"
  movej(get_inverse_kin(p[.109140646997, -.486905511740, .431874337087, .000009529599, -3.141583114199, .000261860116], qnear=[1.570778727531433, -1.570820156727926, 1.5708212852478027, -1.5709641615497034, -1.57080585161318, -2.366701234990387E-5]), a=1.3962634015954636, v=1.0471975511965976)
end
