def P_adminLinearIndex3():
  modbus_add_signal("127.0.0.1", 255, 1, 2, "MODBUS_1", False)
  modbus_set_signal_update_frequency("MODBUS_1", 10)
  modbus_add_signal("127.0.0.1", 255, 128, 0, "atLocation", False)
  modbus_set_signal_update_frequency("atLocation", 10)
  modbus_add_signal("127.0.0.1", 255, 129, 2, "MODBUS_3", False)
  modbus_set_signal_update_frequency("MODBUS_3", 10)
  modbus_add_signal("10.241.34.56", 1, 1009, 3, "MODBUS_2", False)
  modbus_set_signal_update_frequency("MODBUS_2", 10)
  modbus_set_runstate_dependent_choice("MODBUS_2",0)
  set_tool_voltage(0)
  set_gravity([0.0, 0.0, 9.82])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 0)
  set_tool_analog_input_domain(1, 0)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_safety_mode_transition_hardness(0)
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(1.0)
  step_count_a71ffc51_63b1_4ba2_9411_8a1742e93b21 = 0.0
  thread Step_Counter_Thread_e21a6344_0c3d_44bd_9474_b69d71b55b16():
    while (True):
      step_count_a71ffc51_63b1_4ba2_9411_8a1742e93b21 = step_count_a71ffc51_63b1_4ba2_9411_8a1742e93b21 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_e21a6344_0c3d_44bd_9474_b69d71b55b16()
  $ 1 "Robot Program"
  $ 2 "Move_linear_slide_Index1"
  $ 3 "var_1≔ False "
  global var_1=  False  
  $ 4 "Loop var_1≟ False "
  while (var_1 ==   False  ):
    $ 5 "var_1≔socket_open('10.241.34.44',4001)"
    global var_1=socket_open("10.241.34.44",4001)
  end
  $ 6 "var_3≔1"
  global var_3=1
  $ 7 "Send≔'s r0x24 21'"
  global Send="s r0x24 21"
  $ 8 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 9 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 10 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 11 "Send≔'s r0xca 103936'"
  global Send="s r0xca 103936"
  $ 12 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 13 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 14 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 15 "Send≔'t 1'"
  global Send="t 1"
  $ 16 "socket_send_string(Send)"
  socket_send_string(Send)
  $ 17 "socket_send_byte(13)"
  socket_send_byte(13)
  $ 18 "Send_Reply≔socket_read_string()"
  global Send_Reply=socket_read_string()
  $ 19 "Loop var_3≠0"
  while (var_3 != 0):
    $ 20 "Send≔'g r0xA0'"
    global Send="g r0xA0"
    $ 21 "socket_send_string(Send)"
    socket_send_string(Send)
    $ 22 "socket_send_byte(13)"
    socket_send_byte(13)
    $ 23 "var_3≔socket_get_var('v')"
    global var_3=socket_get_var("v")
    $ 24 "Wait: 0.1"
    sleep(0.1)
  end
  $ 25 "socket_close()"
  socket_close()
  $ 26 "sync()"
  sync()
end
